version: '2'

services:
  webapp:
    image: davefelce/portfolio_webapp
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/webapp
    ports:
      - "8005:8001"
      - "8085:8082"
      - "8000:8000"
